# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.0
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: cargo-fmt  # rustup component add rustfmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check --all-features --all-targets --
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy  # rustup component add clippy
        name: cargo clippy
        entry: cargo clippy --tests --all-features -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

ci:
  skip: [cargo-fmt, cargo-check, cargo-clippy]
